drupal8:
  image: drupal:8
  links:
    - db:mariadb
  ports:
    - ${public_port}:80

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: ${mariadb_password}:''
    MYSQL_DATABASE: ${drupal_database}:drupal
    MYSQL_USER: ${drupal_user}:drupal
    MYSQL_PASSWORD: ${drupal_password}:drupal
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

