drupal8:
  image: drupal:8
  links:
    - db:mariadb
  ports:
    - ${public_port}:80

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example
    MYSQL_DATABASE: drupal
    MYSSQL_USER: drupal

